const DEFAULT_PLAYER_NAMES = ["Patryk", "Sandra", "Franio", "Tila", "Marek", "Robobabek"];

const ROLE_META = {
  citizen: { name: "Obywatel", faction: "Miasto", revealText: "Nie masz mocy nocnej. Obserwuj i wyciągaj wnioski.", endColor: "white" },
  mafia: { name: "Mafiozo", faction: "Mafia", revealText: "Grasz z innymi mafiozami i wspólnie eliminujecie resztę!", endColor: "red" },
  doctor: { name: "Lekarz", faction: "Miasto", revealText: "Każdej nocy możesz uratować jednego gracza.", endColor: "blue" },
  detective: { name: "Detektyw", faction: "Miasto", revealText: "Każdej nocy sprawdzasz lojalność jednego gracza.", endColor: "yellow" },
};

const SPECIAL_CARDS = [
  { key: "immunity", name: "Immunitet", group: "A", scope: "all", description: "Anuluje lincz, jeśli miałeś dziś odpaść.", implemented: true },
  { key: "doubleVote", name: "Podwójny Głos", group: "A", scope: "all", description: "Twój głos liczony jest podwójnie.", implemented: true },
  { key: "ricochet", name: "Kozioł Ofiarny", group: "A", scope: "all", description: "Przenosi lincz z pierwszej osoby na drugą w kolejności.", implemented: false },
  { key: "blackmail", name: "Szantaż", group: "A", scope: "all", description: "Ofiara głosuje tak jak wskażesz.", implemented: false },
  { key: "privateDetective", name: "Prywatny Detektyw", group: "B", scope: "all", description: "Prywatnie sprawdzasz frakcję wskazanego gracza.", implemented: false },
  { key: "silence", name: "Nakaz Milczenia", group: "B", scope: "all", description: "Wskazany gracz nie może się odezwać do końca dnia.", implemented: false },
  { key: "steal", name: "Kradzież", group: "B", scope: "all", description: "Kradniesz losową kartę wskazanemu graczowi.", implemented: false },
  { key: "teflon", name: "Fałszywe Alibi", group: "C", scope: "mafia", description: "Sprawdzający zobaczy Cię jako Miasto.", implemented: false },
  { key: "sniper", name: "Snajper", group: "C", scope: "mafia", description: "Natychmiastowy dzienny strzał.", implemented: false },
  { key: "intimidation", name: "Zastraszenie", group: "C", scope: "mafia", description: "Blokujesz nocną akcję ofiary.", implemented: false },
  { key: "vest", name: "Kamizelka Kuloodporna", group: "D", scope: "town", description: "Pierwszy nocny atak mafii nie zabija Cię.", implemented: true },
  { key: "search", name: "Rewizja", group: "D", scope: "town", description: "Publicznie ujawnia jedną kartę ofiary.", implemented: false },
  { key: "convert", name: "Zmiana Stron", group: "D", scope: "town", description: "Może nawrócić mafiozę na Miasto.", implemented: false },
];

const PRESETS = {
  classic: {
    label: "Klasyczna",
    mafiaCount: 2,
    daySeconds: 338,
    votingSeconds: 30,
    nightSeconds: 45,
    startCardsCount: 3,
    enableDoctor: true,
    enableDetective: true,
    enableCards: true,
    enabledCards: Object.fromEntries(SPECIAL_CARDS.map(c => [c.key, true])),
  },
};

const state = {
  players: DEFAULT_PLAYER_NAMES.map(makePlayer),
  selectedPlayerId: "",
  phase: "lobby",
  settings: JSON.parse(JSON.stringify({ ...PRESETS.classic, preset: "classic" })),
  lobbyCountdown: null,
  lobbyEndsAt: null,
  revealCountdown: 30,
  revealEndsAt: null,
  rolePeekActive: false,
  roleCountdownLocked: false,
  phaseSecondsLeft: PRESETS.classic.daySeconds,
  phaseEndsAt: null,
  selectedNightTargetId: "",
  selectedVoteTargetId: "",
  nightActions: {},
  votes: {},
  submittedNightTargets: {},
  pendingNightTargets: {},
  submittedVoteTargets: {},
  transitionData: null,
  transitionLocked: false,
  privateNotes: {},
  nightOrderMap: {},
  voteOrderMap: {},
  activeFlashPlayerId: null,
  dayReadyMap: {},
  winner: null,
  timers: [],
  cardsOverlayOpen: false,
  selectedCardIndex: 0,
  cardPeekActive: false,
  startCardQueue: [],
  grantInfoQueue: [],
  deathGiftQueue: [],
  awaitingDeathGiftFor: null,
  ackFlows: {},
  currentAckKey: "",
};

function makePlayer(name) {
  return { id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2), name, ready: name !== "Patryk", alive: true, role: null, faction: null, roleRevealed: false, roleAcknowledged: false, nightSubmitted: false, voteSubmitted: false, immunityActive:false, vestActive:false, doubleVoteArmed:false, cards: [] };
}
function clearAllTimers(){state.timers.forEach(clearTimeout);state.timers=[]}
function later(fn,ms){const id=setTimeout(fn,ms);state.timers.push(id);return id}
function shuffle(arr){const copy=[...arr];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function formatSeconds(total){const clamped=Math.max(0,total);const minutes=Math.floor(clamped/60);const seconds=clamped%60;return `${minutes}:${String(seconds).padStart(2,"0")}`}
function secondsLeftFromEnd(endAt){if(!endAt)return 0;return Math.max(0,Math.ceil((endAt-Date.now())/1000))}
function selectedPlayer(){return state.players.find(p=>p.id===state.selectedPlayerId)||state.players[0]||null}
function mafiaActorIds(){return state.players.filter(p=>p.role==="mafia").map(p=>p.id)}
function alivePlayers(players=state.players){return players.filter(p=>p.alive)}
function aliveMafiaActorIds(players=state.players){return alivePlayers(players).filter(p=>p.role==="mafia").map(p=>p.id)}
function targetGenderText(name,male,female){return name.trim().toLowerCase().endsWith("a")?female:male}
function getRoleTeamText(player,players){if(!player||!player.role||player.role!=="mafia"){return player&&player.role?ROLE_META[player.role].revealText:""}const teammates=players.filter(p=>p.id!==player.id&&p.role==="mafia").map(p=>p.name).join(", ");return teammates?`${teammates} gra z Tobą, wyeliminujcie resztę!`:ROLE_META.mafia.revealText}
function countTargetsFromActors(targetMap, allowedActors){return Object.entries(targetMap).reduce((acc,[actorId,targetId])=>{if(!allowedActors.includes(actorId))return acc;acc[targetId]=(acc[targetId]||0)+1;return acc},{})}
function getConsensusTargetId(targetMap, actorIds){const ranked=Object.entries(countTargetsFromActors(targetMap, actorIds)).sort((a,b)=>b[1]-a[1]);if(!ranked.length)return null;if(ranked.length>1&&ranked[0][1]===ranked[1][1])return null;return ranked[0][0]}
function getWinner(players){const alive=players.filter(p=>p.alive);const mafiaAlive=alive.filter(p=>p.faction==="Mafia").length;const townAlive=alive.filter(p=>p.faction==="Miasto").length;if(mafiaAlive===0)return "Miasto";if(mafiaAlive>=townAlive)return "Mafia";return null}
function generateRoles(players, settings){const total=players.length;const roles=[];const mafiaCount=Math.min(settings.mafiaCount,Math.max(1,total-2));for(let i=0;i<mafiaCount;i++)roles.push("mafia");if(settings.enableDoctor&&roles.length<total)roles.push("doctor");if(settings.enableDetective&&roles.length<total)roles.push("detective");while(roles.length<total)roles.push("citizen");return shuffle(roles)}
function pulseFade(next){const fade=document.getElementById("fade");fade.classList.add("show");later(()=>{if(next)next();later(()=>fade.classList.remove("show"),220)},300)}
function chooseAndFlashPlayer(playerId,setter,afterSet){setter(playerId);if(afterSet)afterSet(playerId);state.activeFlashPlayerId=playerId;render();later(()=>{if(state.activeFlashPlayerId===playerId){state.activeFlashPlayerId=null;render()}},1000)}
function buildPerPlayerOrder(){const next={};state.players.forEach((viewer,viewerIdx)=>{const shuffled=shuffle([...state.players]);next[viewer.id]=shuffled.map((_,idx,arr)=>arr[(idx+viewerIdx)%arr.length])});return next}
function resetReady(){state.players=state.players.map(p=>({...p,ready:false}));render()}
function canUseCard(card){if(!card)return false; return !card.used}
function activeCardPool(){if(!state.settings.enableCards) return []; return SPECIAL_CARDS.filter(c=>state.settings.enabledCards[c.key])}
function createCardInstance(key, source){const meta=SPECIAL_CARDS.find(c=>c.key===key); return { instanceId:(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)), key, source, used:false, delivered:false, seen:false, meta }}
function giveCardToPlayer(playerId, key, source){const player=state.players.find(p=>p.id===playerId); if(!player) return null; const instance=createCardInstance(key, source); player.cards.push(instance); return instance}
function dealStartCards(){const pool=activeCardPool(); if(!pool.length||!state.settings.enableCards||state.settings.startCardsCount<=0) return; const count=Math.min(state.settings.startCardsCount, state.players.length,  pool.length*10); const receivers=shuffle([...state.players]).slice(0, Math.min(count,state.players.length)); const queue=[]; receivers.forEach((player, idx)=>{const cardMeta=pool[Math.floor(Math.random()*pool.length)]; const instance=giveCardToPlayer(player.id, cardMeta.key, "start"); queue.push({playerId:player.id, cardInstanceId:instance.instanceId, type:"received"});}); state.players.forEach(player=>{if(!receivers.some(r=>r.id===player.id)){queue.push({playerId:player.id, type:"none"});}}); state.startCardQueue=queue;}
function getPlayerCardById(player, instanceId){return player.cards.find(c=>c.instanceId===instanceId)}
function hiddenCardHTML(){return `<div class="card-shell card-back centered"><div class="card-back-question">?</div></div>`}
function cardFaceHTML(card){const meta=card.meta||SPECIAL_CARDS.find(c=>c.key===card.key); return `<div class="card-shell"><div class="card-face"><div><div class="card-face-top">Karta specjalna</div><div class="card-face-name">${meta.name}</div><div class="card-face-group">Grupa ${meta.group}</div></div><div class="card-face-desc">${meta.description}</div></div></div>`}
function ensureAckFlow(key){if(!state.ackFlows[key]){state.ackFlows[key]={}}state.currentAckKey=key;return state.ackFlows[key]}
function clearAckFlow(key){delete state.ackFlows[key];if(state.currentAckKey===key){state.currentAckKey=""}}
function ackCountTextByKey(key, aliveOnly=false){const ackMap=state.ackFlows[key]||{};const pool=aliveOnly?state.players.filter(p=>p.alive):state.players;const total=pool.length;const done=pool.filter(p=>ackMap[p.id]).length;return `${done}/${total}`}
function isAckedInFlow(key, playerId){const ackMap=state.ackFlows[key]||{};return !!ackMap[playerId]}
function acknowledgeFlow(key,onEveryoneDone,aliveOnly=false){const sp=selectedPlayer();if(!sp)return;const ackMap=ensureAckFlow(key);const pool=aliveOnly?state.players.filter(p=>p.alive):state.players;if(!pool.some(p=>p.id===sp.id))return;if(ackMap[sp.id]) return;ackMap[sp.id]=true;render();const everyoneDone=pool.every(p=>ackMap[p.id]);if(everyoneDone){clearAckFlow(key);onEveryoneDone()}}
function bindPress(element, handler){if(!element)return;let pointerHandled=false;element.addEventListener("pointerup",(e)=>{e.preventDefault();pointerHandled=true;handler(e);later(()=>{pointerHandled=false},50)});element.addEventListener("click",(e)=>{if(pointerHandled){e.preventDefault();return}e.preventDefault();handler(e)})}
function bindPressAll(nodeList, handler){nodeList.forEach(el=>bindPress(el, handler))}

function maybeStartStartCardFlow(){ if(state.startCardQueue.length){ state.phase="startCardInfo"; render(); return true; } return false; }
function nextStartCardInfo(){ state.startCardQueue=[]; clearAckFlow("start-card-flow"); startNight(); }
function startGrantInfoQueue(targetPlayerId){ const queue=[]; state.players.forEach(p=>{ if(!p.alive) return; if(p.id===targetPlayerId){ const undelivered=p.cards.find(c=>!c.delivered && c.source==="deathGift"); if(undelivered){ undelivered.delivered=true; queue.push({playerId:p.id,type:"received",cardInstanceId:undelivered.instanceId}); return; } } queue.push({playerId:p.id,type:"none"}); }); state.grantInfoQueue=queue; state.phase="grantInfo"; clearAckFlow("grant-card-flow"); render(); }
function nextGrantInfo(){ state.grantInfoQueue=[]; clearAckFlow("grant-card-flow"); state.phase="night"; state.phaseEndsAt=Date.now()+state.settings.nightSeconds*1000; state.phaseSecondsLeft=secondsLeftFromEnd(state.phaseEndsAt); render(); schedulePhaseTick(); }

function selectNextPlayer(){if(!state.players.length)return;const idx=Math.max(0,state.players.findIndex(p=>p.id===state.selectedPlayerId));const next=(idx+1)%state.players.length;state.selectedPlayerId=state.players[next].id;render()}
function addPlayer(){const input=document.getElementById("joinNameInput");const trimmed=input.value.trim();if(!trimmed)return;if(state.players.length>=12)return;if(state.players.some(p=>p.name.toLowerCase()===trimmed.toLowerCase()))return;state.players.push(makePlayer(trimmed));input.value="";closeJoinModal();if(!state.selectedPlayerId&&state.players[0])state.selectedPlayerId=state.players[0].id;render()}
function toggleReady(id){if(state.phase!=="lobby")return;state.players=state.players.map(p=>p.id===id?{...p,ready:!p.ready}:p);render();checkLobbyCountdown()}
function startGame(){const roles=generateRoles(state.players,state.settings);state.players=state.players.map((p,index)=>({...p,alive:true,role:roles[index],faction:roles[index]==="mafia"?"Mafia":"Miasto",roleRevealed:false,roleAcknowledged:false,ready:false,nightSubmitted:false,voteSubmitted:false,immunityActive:false,vestActive:false,doubleVoteArmed:false,cards:[]}));state.phase="roleReveal";state.rolePeekActive=false;state.winner=null;state.nightActions={};state.votes={};state.submittedVoteTargets={};state.submittedNightTargets={};state.pendingNightTargets={};state.privateNotes={};state.selectedVoteTargetId="";state.selectedNightTargetId="";state.revealEndsAt=Date.now()+30000;state.revealCountdown=secondsLeftFromEnd(state.revealEndsAt);state.roleCountdownLocked=false;state.transitionData=null;state.transitionLocked=false;state.dayReadyMap={};state.lobbyCountdown=null;state.lobbyEndsAt=null;dealStartCards();render();scheduleRoleRevealTick()}
function revealRole(){const sp=selectedPlayer();if(!sp)return;state.players=state.players.map(p=>p.id===sp.id?{...p,roleRevealed:true}:p);render()}
function setPeek(active){state.rolePeekActive=active;if(active)revealRole();render()}
function acknowledgeRole(){const sp=selectedPlayer();if(!sp||sp.roleAcknowledged)return;state.players=state.players.map(p=>p.id===sp.id?{...p,roleAcknowledged:true}:p);render();if(state.players.every(p=>p.roleAcknowledged||p.id===sp.id)){later(()=>{if(state.players.every(p=>p.roleAcknowledged)){state.roleCountdownLocked=true;pulseFade(()=>{ if(!maybeStartStartCardFlow()) startNight();});}},0)}}
function startNight(){state.nightOrderMap=buildPerPlayerOrder();state.phase="night";state.phaseEndsAt=Date.now()+state.settings.nightSeconds*1000;state.phaseSecondsLeft=secondsLeftFromEnd(state.phaseEndsAt);state.nightActions={};state.submittedNightTargets={};state.pendingNightTargets={};state.selectedNightTargetId="";state.activeFlashPlayerId=null;state.cardsOverlayOpen=false;state.privateNotes={};state.players=state.players.map(p=>({...p,nightSubmitted:false,voteSubmitted:false}));render();schedulePhaseTick()}
function submitNightAction(){const sp=selectedPlayer();if(!sp||!sp.alive||!state.selectedNightTargetId||sp.nightSubmitted)return;const actionType=sp.role==="mafia"?"kill":sp.role==="doctor"?"heal":sp.role==="detective"?"inspect":"dummy";state.nightActions[sp.id]={actorId:sp.id,targetId:state.selectedNightTargetId,actionType,submitted:true};if(sp.role==="mafia"){state.submittedNightTargets[sp.id]=state.selectedNightTargetId;delete state.pendingNightTargets[sp.id]}state.selectedNightTargetId="";state.players=state.players.map(p=>p.id===sp.id?{...p,nightSubmitted:true}:p);render();const livingPlayers=alivePlayers();const allAliveDone=livingPlayers.every(p=>p.nightSubmitted);if(allAliveDone){pulseFade(()=>resolveNightWithActions({...state.nightActions},[...state.players]))}}
function showTransition(data){state.transitionLocked=false;state.dayReadyMap={};state.transitionData=data;state.phase="transition";render()}
function resolveNightWithActions(actionsArg,playersArg){const basePlayers=playersArg||state.players;const actionList=Object.values(actionsArg||state.nightActions);const livingMafiaIds=aliveMafiaActorIds(basePlayers);const mafiaTargetId=getConsensusTargetId(Object.fromEntries(actionList.filter(a=>a.actionType==="kill").map(a=>[a.actorId,a.targetId])),livingMafiaIds);const healAction=actionList.find(a=>a.actionType==="heal");const inspectAction=actionList.find(a=>a.actionType==="inspect");let nextPlayers=basePlayers.map(p=>({...p,nightSubmitted:false}));const notes={};let killedName="Nikt";if(inspectAction){const target=nextPlayers.find(p=>p.id===inspectAction.targetId);if(target){notes[inspectAction.actorId]=`${target.name} ${target.faction==="Mafia"?"jest":"nie jest"} z mafii.`}}if(mafiaTargetId){const target=nextPlayers.find(p=>p.id===mafiaTargetId);const saved=healAction&&healAction.targetId===mafiaTargetId;const hasVest=target&&target.vestActive;if(target&&!saved&&!hasVest){nextPlayers=nextPlayers.map(p=>p.id===target.id?{...p,alive:false}:p);killedName=target.name}else if(target&&hasVest){nextPlayers=nextPlayers.map(p=>p.id===target.id?{...p,vestActive:false}:p);killedName="Nikt";notes[target.id]="Kamizelka ochroniła Cię przed atakiem."}}state.players=nextPlayers;state.privateNotes=notes;state.selectedNightTargetId="";state.pendingNightTargets={};state.activeFlashPlayerId=null;const maybeWinner=getWinner(nextPlayers);if(maybeWinner){pulseFade(()=>{state.winner=maybeWinner;state.phase="ended";render()});return}showTransition({title:"Nastał dzień",message:killedName==="Nikt"?"Tej nocy nikt nie zginął.":`${killedName}\n${targetGenderText(killedName,"został wyeliminowany","została wyeliminowana")}\nprzez mafię.`,button:"Ok",nextPhase:"day"})}
function resolveNight(){resolveNightWithActions()}
function startVoting(){state.voteOrderMap=buildPerPlayerOrder();state.phase="voting";state.phaseEndsAt=Date.now()+state.settings.votingSeconds*1000;state.phaseSecondsLeft=secondsLeftFromEnd(state.phaseEndsAt);state.votes={};state.submittedVoteTargets={};state.selectedVoteTargetId="";state.activeFlashPlayerId=null;state.cardsOverlayOpen=false;state.players=state.players.map(p=>({...p,voteSubmitted:false}));render();schedulePhaseTick()}
function submitVote(){const sp=selectedPlayer();if(!sp||!sp.alive||!state.selectedVoteTargetId||sp.voteSubmitted)return;state.votes[sp.id]=state.selectedVoteTargetId;state.submittedVoteTargets[sp.id]=state.selectedVoteTargetId;state.players=state.players.map(p=>p.id===sp.id?{...p,voteSubmitted:true}:p);render();const livingPlayers=alivePlayers();const allAliveDone=livingPlayers.every(p=>p.voteSubmitted);if(allAliveDone){pulseFade(()=>resolveVoting())}}
function resolveVoting(){const counts={};Object.entries(state.votes).forEach(([actorId,targetId])=>{const actor=state.players.find(p=>p.id===actorId);const weight=actor&&actor.doubleVoteArmed?2:1;counts[targetId]=(counts[targetId]||0)+weight});const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let nextPlayers=state.players.map(p=>({...p,voteSubmitted:false,doubleVoteArmed:false}));let eliminatedName="Nikt";let eliminatedId=null;if(ranked.length===1||(ranked.length>1&&ranked[0][1]>ranked[1][1])){eliminatedId=ranked[0][0];const protectedTarget=nextPlayers.find(p=>p.id===eliminatedId&&p.immunityActive);if(protectedTarget){nextPlayers=nextPlayers.map(p=>p.id===eliminatedId?{...p,immunityActive:false}:p);eliminatedId=null;eliminatedName="Nikt";}else{nextPlayers=nextPlayers.map(p=>p.id===eliminatedId?{...p,alive:false}:p);const eliminated=nextPlayers.find(p=>p.id===eliminatedId);if(eliminated)eliminatedName=eliminated.name}}state.players=nextPlayers;state.selectedVoteTargetId="";state.activeFlashPlayerId=null;const maybeWinner=getWinner(nextPlayers);if(maybeWinner){pulseFade(()=>{state.winner=maybeWinner;state.phase="ended";render()});return}
 if(eliminatedId && state.settings.enableCards && activeCardPool().length){const dead=state.players.find(p=>p.id===eliminatedId);const aliveTargets=state.players.filter(p=>p.alive); if(dead && aliveTargets.length){ const cardMeta=activeCardPool()[Math.floor(Math.random()*activeCardPool().length)]; const instance=createCardInstance(cardMeta.key, "deathGift"); dead.cards.push(instance); state.awaitingDeathGiftFor={deadPlayerId:dead.id, cardInstanceId:instance.instanceId}; state.phase="deathGiftChoose"; render(); return; }}
 showTransition({title:"Nadchodzi noc",message:eliminatedName==="Nikt"?"Nikt nie został wyrzucony\nprzez graczy.":`${eliminatedName}\n${targetGenderText(eliminatedName,"został wyrzucony","została wyrzucona")}\nprzez graczy.`,button:"Ok",nextPhase:"night"})}
function handleTransitionConfirm(){if(!state.transitionData||state.transitionLocked)return;state.transitionLocked=true;render();pulseFade(()=>{const next=state.transitionData.nextPhase;state.transitionData=null;state.transitionLocked=false;if(next==="day"){state.phase="day";state.phaseEndsAt=Date.now()+state.settings.daySeconds*1000;state.phaseSecondsLeft=secondsLeftFromEnd(state.phaseEndsAt);render();schedulePhaseTick()}else if(next==="night"){startNight()}else{state.phase="ended";render()}})}
function markReadyForVoting(){const sp=selectedPlayer();if(!sp||!sp.alive)return;state.dayReadyMap[sp.id]=true;render();const livingPlayers=alivePlayers();if(livingPlayers.every(p=>state.dayReadyMap[p.id])){pulseFade(()=>startVoting())}}
function resetGame(){state.players=state.players.map(p=>makePlayer(p.name));state.selectedPlayerId=state.players[0]?state.players[0].id:"";state.phase="lobby";state.lobbyCountdown=null;state.lobbyEndsAt=null;state.rolePeekActive=false;state.revealCountdown=30;state.revealEndsAt=null;state.roleCountdownLocked=false;state.phaseSecondsLeft=state.settings.daySeconds;state.phaseEndsAt=null;state.nightActions={};state.votes={};state.submittedVoteTargets={};state.submittedNightTargets={};state.pendingNightTargets={};state.privateNotes={};state.winner=null;state.selectedVoteTargetId="";state.selectedNightTargetId="";state.transitionData=null;state.transitionLocked=false;state.dayReadyMap={};state.nightOrderMap={};state.voteOrderMap={};state.activeFlashPlayerId=null;state.cardsOverlayOpen=false;state.selectedCardIndex=0;state.cardPeekActive=false;state.startCardQueue=[];state.grantInfoQueue=[];state.awaitingDeathGiftFor=null;state.ackFlows={};state.currentAckKey="";clearAllTimers();render()}
function checkLobbyCountdown(){if(state.phase!=="lobby")return;const readyCount=state.players.filter(p=>p.ready).length;const everyoneReady=state.players.length>=4&&readyCount===state.players.length;if(!everyoneReady){state.lobbyCountdown=null;state.lobbyEndsAt=null;render();return}if(state.lobbyEndsAt!==null)return;state.lobbyEndsAt=Date.now()+3000;state.lobbyCountdown=secondsLeftFromEnd(state.lobbyEndsAt);render();const tick=()=>{if(state.phase!=="lobby"||state.lobbyEndsAt===null)return;const remaining=secondsLeftFromEnd(state.lobbyEndsAt);state.lobbyCountdown=remaining;render();if(remaining<=0){pulseFade(()=>{state.lobbyCountdown=null;state.lobbyEndsAt=null;startGame()});return}later(tick,250)};later(tick,250)}
function scheduleRoleRevealTick(){const tick=()=>{if(state.phase!=="roleReveal")return;if(state.roleCountdownLocked)return;if(!state.revealEndsAt)return;const remaining=secondsLeftFromEnd(state.revealEndsAt);state.revealCountdown=remaining;render();if(remaining<=0){state.roleCountdownLocked=true;pulseFade(()=>{if(!maybeStartStartCardFlow()) startNight()});return}later(tick,250)};later(tick,250)}
function schedulePhaseTick(){const tick=()=>{if(!["night","day","voting"].includes(state.phase))return;if(state.transitionData)return;if(!state.phaseEndsAt)return;const remaining=secondsLeftFromEnd(state.phaseEndsAt);state.phaseSecondsLeft=remaining;render();if(remaining<=0){if(state.phase==="night")resolveNight();else if(state.phase==="day")startVoting();else if(state.phase==="voting")resolveVoting();return}later(tick,250)};later(tick,250)}
function userIconSVG(size=16){return `<svg viewBox="0 0 24 24" width="${size}" height="${size}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 21a8 8 0 0 0-16 0"></path><circle cx="12" cy="7" r="4"></circle></svg>`}
function eyeIconSVG(size=64){return `<svg viewBox="0 0 24 24" width="${size}" height="${size}" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"></path><circle cx="12" cy="12" r="3"></circle></svg>`}
function crosshairIconText(){return `<svg viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="display:block"><circle cx="12" cy="12" r="6"></circle><path d="M12 3v3"></path><path d="M12 18v3"></path><path d="M3 12h3"></path><path d="M18 12h3"></path></svg>`}
function tileHTML(player,opts={}){const{showReady=false,voteCount=0,pendingCount=0,disabled=false,flash=false,muted=false,pendingTarget=false,showPlus=false}=opts;if(showPlus){return `<button class="tile" data-plus="1"><div class="tile-left"><span style="display:flex;align-items:center;justify-content:center">${userIconSVG(14)}</span><span class="tile-name">Dołącz</span></div></button>`}if(!player)return "";const extraClasses=[disabled?"disabled":"",flash?"flash":"",muted?"is-muted":"",muted?"dead":""].join(" ");return `<button class="tile ${extraClasses}" data-player-id="${player.id}" ${disabled?"disabled":""}><div class="tile-left"><span style="display:flex;align-items:center;justify-content:center">${userIconSVG(14)}</span><span class="tile-name">${player.name}</span></div><div class="tile-right">${pendingTarget&&pendingCount>0?`<span class="pending">${crosshairIconText()} <span>${pendingCount}</span></span>`:""}${voteCount>0?`<span class="count">${voteCount}</span>`:""}${showReady&&player.ready?`<span class="count">✓</span>`:""}</div></button>`}
function canOpenCards(player){return !!player&&player.cards.some(card=>!card.used)}
function bottomHTML({metaLines=["&nbsp;"],secondaryLabel="Karty",secondaryDisabled=true,secondaryVisible=true,secondaryId="secondaryBtn",primaryLabel="Ok",primaryDisabled=false,primaryId="mainBtn"}){const secondary=secondaryVisible?`<button id="${secondaryId}" class="text-action" ${secondaryDisabled?"disabled":""}>${secondaryLabel}</button>`:`<div class="text-action text-action-placeholder" aria-hidden="true"></div>`;return `<div class="bottom"><div class="bottom-meta">${metaLines.map(line=>`<div class="bottom-meta-line">${line}</div>`).join("")}</div><div class="bottom-secondary-slot">${secondary}</div><button id="${primaryId}" class="primary" ${primaryDisabled?"disabled":""}>${primaryLabel}</button></div>`}
function bindCardsShortcut(sp){const btn=document.getElementById("secondaryBtn");if(!btn||btn.disabled)return;bindPress(btn,()=>{state.cardsOverlayOpen=true;state.selectedCardIndex=0;render()})}

function renderLobby(screen,sp){const readyCount=state.players.filter(p=>p.ready).length;const emptySlots=Math.max(0,12-state.players.length);screen.innerHTML=`<div class="title-top">Mafia</div><div class="big-title">Lobby</div><div class="subcount">${state.players.length}/12</div><div class="grid" id="lobbyGrid"></div>${bottomHTML({metaLines:[state.lobbyCountdown===null?`${readyCount}/${state.players.length}`:`0:${String(state.lobbyCountdown).padStart(2,"0")}`],secondaryVisible:false,primaryLabel:sp&&sp.ready?"Gotowy":"Start"})}`;const grid=document.getElementById("lobbyGrid");grid.innerHTML=state.players.slice(0,12).map(p=>tileHTML(p,{showReady:true})).join("")+Array.from({length:emptySlots}).map(()=>tileHTML(null,{showPlus:true})).join("");bindPressAll(grid.querySelectorAll("[data-plus]"),()=>openJoinModal());bindPress(document.getElementById("mainBtn"),()=>{if(sp)toggleReady(sp.id)})}
function renderRoleReveal(screen,sp){const ackCount=state.players.filter(p=>p.roleAcknowledged).length;screen.innerHTML=`<div class="title-top">Twoja rola</div><div class="role-name">${state.rolePeekActive&&sp.role?ROLE_META[sp.role].name:"****"}</div><div class="role-desc">${state.rolePeekActive?getRoleTeamText(sp,state.players):""}</div><div class="eye-wrap"><button id="eyeBtn" class="eye-btn" aria-label="Pokaż rolę">${eyeIconSVG(64)}</button></div>${bottomHTML({metaLines:[formatSeconds(state.revealCountdown),`${ackCount}/${state.players.length}`],secondaryVisible:false,primaryLabel:"Ok",primaryDisabled:sp.roleAcknowledged})}`;const eyeBtn=document.getElementById("eyeBtn");eyeBtn.addEventListener("pointerdown",(e)=>{e.preventDefault();setPeek(true)});const hideRole=(e)=>{e.preventDefault();setPeek(false)};eyeBtn.addEventListener("pointerup",hideRole);eyeBtn.addEventListener("pointercancel",hideRole);eyeBtn.addEventListener("pointerleave",hideRole);bindPress(document.getElementById("mainBtn"),()=>acknowledgeRole())}
function renderCardInfo(screen){const sp=selectedPlayer();const item=state.startCardQueue.find(q=>q.playerId===sp.id)||{type:"none"};const ackKey="start-card-flow";ensureAckFlow(ackKey);const already=isAckedInFlow(ackKey,sp.id);let title=item.type==="received"?"Otrzymałeś kartę specjalną":"Nie dostałeś karty specjalnej.";let cardHtml="";if(item.type==="received"){const card=getPlayerCardById(sp,item.cardInstanceId);cardHtml=`<div class="card-stage-wrap">${state.cardPeekActive?cardFaceHTML(card):hiddenCardHTML()}</div><div class="eye-wrap" style="flex:0 0 auto"><button id="eyeBtn" class="eye-btn" aria-label="Pokaż kartę">${eyeIconSVG(56)}</button></div>`}screen.innerHTML=`<div class="title-top">Start gry</div><div class="info-text">${title}</div>${cardHtml||'<div class="card-stage-wrap"><div class="helper-note">Brak karty na start.</div></div>'}${bottomHTML({metaLines:[ackCountTextByKey(ackKey)],secondaryVisible:false,primaryLabel:"Ok",primaryDisabled:already})}`;const eyeBtn=document.getElementById("eyeBtn");if(eyeBtn){eyeBtn.addEventListener("pointerdown",(e)=>{e.preventDefault();state.cardPeekActive=true;render()});const hide=(e)=>{e.preventDefault();state.cardPeekActive=false;render()};eyeBtn.addEventListener("pointerup",hide);eyeBtn.addEventListener("pointercancel",hide);eyeBtn.addEventListener("pointerleave",hide)}bindPress(document.getElementById("mainBtn"),()=>acknowledgeFlow(ackKey,()=>{state.cardPeekActive=false;nextStartCardInfo()}))}
function renderDeathGiftChoose(screen, sp){const dead=state.players.find(p=>p.id===state.awaitingDeathGiftFor.deadPlayerId);const card=getPlayerCardById(dead,state.awaitingDeathGiftFor.cardInstanceId);screen.innerHTML=`<div class="title-top">Dar z Zaświatów</div><div class="info-text">Wybierz żyjącego gracza, któremu przekażesz kartę.</div><div class="card-stage-wrap">${state.cardPeekActive?cardFaceHTML(card):hiddenCardHTML()}</div><div class="eye-wrap" style="flex:0 0 auto"><button id="eyeBtn" class="eye-btn" aria-label="Pokaż kartę">${eyeIconSVG(56)}</button></div><div class="grid" id="giftGrid"></div>${bottomHTML({metaLines:["&nbsp;"],secondaryVisible:false,primaryLabel:"Przekaż",primaryDisabled:!state.selectedNightTargetId})}`;const grid=document.getElementById("giftGrid");grid.innerHTML=state.players.filter(p=>p.alive).map(player=>tileHTML(player,{flash:state.activeFlashPlayerId===player.id})).join("");bindPressAll(grid.querySelectorAll("[data-player-id]"),(e)=>{const id=e.currentTarget.getAttribute("data-player-id");chooseAndFlashPlayer(id,(value)=>{state.selectedNightTargetId=value;render()})});const eyeBtn=document.getElementById("eyeBtn");eyeBtn.addEventListener("pointerdown",(e)=>{e.preventDefault();state.cardPeekActive=true;render()});const hide=(e)=>{e.preventDefault();state.cardPeekActive=false;render()};eyeBtn.addEventListener("pointerup",hide);eyeBtn.addEventListener("pointercancel",hide);eyeBtn.addEventListener("pointerleave",hide);bindPress(document.getElementById("mainBtn"),()=>{const target=state.players.find(p=>p.id===state.selectedNightTargetId);if(!target) return; const instance=getPlayerCardById(dead,state.awaitingDeathGiftFor.cardInstanceId); dead.cards=dead.cards.filter(c=>c.instanceId!==instance.instanceId); target.cards.push({...instance, delivered:false, source:"deathGift"}); state.awaitingDeathGiftFor=null; state.selectedNightTargetId=""; state.cardPeekActive=false; startGrantInfoQueue(target.id); })}
function renderGrantInfo(screen, sp){const item=state.grantInfoQueue.find(q=>q.playerId===sp.id);if(!item){screen.innerHTML="";return;}const ackKey="grant-card-flow";ensureAckFlow(ackKey);const already=isAckedInFlow(ackKey,sp.id);let main='';if(item.type==='received'){const card=sp.cards.find(c=>c.instanceId===item.cardInstanceId);main=`<div class="info-text">Otrzymałeś kartę specjalną.</div><div class="card-stage-wrap">${state.cardPeekActive?cardFaceHTML(card):hiddenCardHTML()}</div><div class="eye-wrap" style="flex:0 0 auto"><button id="eyeBtn" class="eye-btn" aria-label="Pokaż kartę">${eyeIconSVG(56)}</button></div>`;} else {main=`<div class="card-stage-wrap"><div class="helper-note">Żaden gracz nie przekazał ci karty.</div></div>`;}screen.innerHTML=`<div class="title-top">Nowa karta</div>${main}${bottomHTML({metaLines:[ackCountTextByKey(ackKey,true)],secondaryVisible:false,primaryLabel:"Ok",primaryDisabled:already})}`;const eyeBtn=document.getElementById('eyeBtn');if(eyeBtn){eyeBtn.addEventListener('pointerdown',(e)=>{e.preventDefault();state.cardPeekActive=true;render()});const hide=(e)=>{e.preventDefault();state.cardPeekActive=false;render()};eyeBtn.addEventListener('pointerup',hide);eyeBtn.addEventListener('pointercancel',hide);eyeBtn.addEventListener('pointerleave',hide)}bindPress(document.getElementById('mainBtn'),()=>acknowledgeFlow(ackKey,()=>{state.cardPeekActive=false;nextGrantInfo()},true)); }
function renderNight(screen,sp){const order=state.nightOrderMap[sp.id]||state.players;const isDead=!sp.alive;const alreadySubmitted=!!sp.nightSubmitted;const hasCards=canOpenCards(sp);const title=sp.role==="mafia"?"Wybierz osobę do eliminacji":sp.role==="doctor"?"Wybierz osobę do ochrony":sp.role==="detective"?"Wybierz osobę do sprawdzenia":"Kogo podejrzewasz?";const nightCounts=countTargetsFromActors(state.submittedNightTargets,mafiaActorIds());const pendingNightCounts=countTargetsFromActors(state.pendingNightTargets,mafiaActorIds());screen.innerHTML=`<div class="title-top">Noc</div><div class="timer">${formatSeconds(state.phaseSecondsLeft)}</div><div class="info-text">${isDead?"Nie żyjesz, nie bierzesz udziału w akcji nocnej":alreadySubmitted?"Twój wybór został już zatwierdzony":title}</div><div class="grid" id="nightGrid"></div>${bottomHTML({metaLines:["&nbsp;"],secondaryLabel:"Karty",secondaryDisabled:false,secondaryVisible:hasCards,primaryLabel:"Gotowe",primaryDisabled:isDead||alreadySubmitted||!state.selectedNightTargetId})}`;const grid=document.getElementById("nightGrid");grid.innerHTML=order.map((player)=>{const detectiveSelfBlocked=sp.role==="detective"&&player.id===sp.id;const hardDisabled=isDead||!player.alive||alreadySubmitted;const muted=isDead||!player.alive||alreadySubmitted;const disabled=hardDisabled||detectiveSelfBlocked;return tileHTML(player,{voteCount:sp.role==="mafia"&&!isDead?(nightCounts[player.id]||0):0,pendingCount:sp.role==="mafia"&&!isDead?(pendingNightCounts[player.id]||0):0,pendingTarget:sp.role==="mafia"&&!isDead&&(pendingNightCounts[player.id]||0)>0,flash:state.activeFlashPlayerId===player.id,muted,disabled})}).join("");bindPressAll(grid.querySelectorAll("[data-player-id]"),(e)=>{if(alreadySubmitted||isDead)return;const id=e.currentTarget.getAttribute("data-player-id");const target=state.players.find((p)=>p.id===id);if(!target||!target.alive)return;if(sp.role==="detective"&&id===sp.id)return;chooseAndFlashPlayer(id,(value)=>{state.selectedNightTargetId=value;render()},(value)=>{if(sp.role==="mafia"&&!sp.nightSubmitted){state.pendingNightTargets[sp.id]=value;render()}})});bindCardsShortcut(sp);bindPress(document.getElementById("mainBtn"),()=>submitNightAction());if(state.cardsOverlayOpen) renderCardsOverlay(screen, sp)}
function renderDay(screen,sp){const livingPlayers=alivePlayers();const isDead=!sp.alive;const hasCards=canOpenCards(sp);const readyCount=livingPlayers.filter((p)=>state.dayReadyMap[p.id]).length;screen.innerHTML=`<div class="title-top">Obrady</div><div class="timer">${formatSeconds(state.phaseSecondsLeft)}</div><div class="info-text" style="flex:1;display:flex;align-items:center;justify-content:center;padding:0 18px">${isDead?"Nie żyjesz, nie bierzesz udziału w obradach i głosowaniu.":"Trwają obrady, ustalcie wspólnie kto jest członkiem mafii."}</div>${bottomHTML({metaLines:[`${readyCount}/${livingPlayers.length}`],secondaryLabel:"Karty",secondaryDisabled:false,secondaryVisible:hasCards,primaryLabel:"Do głosowania",primaryDisabled:!sp||isDead||state.dayReadyMap[sp.id]})}`;bindCardsShortcut(sp);bindPress(document.getElementById("mainBtn"),()=>markReadyForVoting());if(state.cardsOverlayOpen) renderCardsOverlay(screen, sp)}
function renderVoting(screen,sp){const order=state.voteOrderMap[sp.id]||state.players;const isDead=!sp.alive;const hasCards=canOpenCards(sp);const voteCounts=Object.values(state.submittedVoteTargets).reduce((acc,id)=>{acc[id]=(acc[id]||0)+1;return acc},{}) ;screen.innerHTML=`<div class="title-top">Głosowanie</div><div class="timer">${formatSeconds(state.phaseSecondsLeft)}</div><div class="info-text">${isDead?"Nie żyjesz, nie bierzesz udziału w głosowaniu":"Twoja kolej na oddanie głosu"}</div><div class="grid" id="voteGrid"></div>${bottomHTML({metaLines:["&nbsp;"],secondaryLabel:"Karty",secondaryDisabled:false,secondaryVisible:hasCards,primaryLabel:"Gotowe",primaryDisabled:isDead||sp.voteSubmitted||!state.selectedVoteTargetId})}`;const grid=document.getElementById("voteGrid");grid.innerHTML=order.map((player)=>{const playerDisabled=!player.alive||isDead;const playerMuted=!player.alive||isDead;return tileHTML(player,{voteCount:voteCounts[player.id]||0,flash:player.alive&&state.activeFlashPlayerId===player.id,muted:playerMuted,disabled:playerDisabled})}).join("");bindPressAll(grid.querySelectorAll("[data-player-id]"),(e)=>{if(isDead||sp.voteSubmitted)return;const id=e.currentTarget.getAttribute("data-player-id");const target=state.players.find((p)=>p.id===id);if(!target||!target.alive)return;chooseAndFlashPlayer(id,(value)=>{state.selectedVoteTargetId=value;render()})});bindCardsShortcut(sp);bindPress(document.getElementById("mainBtn"),()=>submitVote());if(state.cardsOverlayOpen) renderCardsOverlay(screen, sp)}
function applyCardEffect(player, card){if(!player||!card||card.used)return {ok:false};if(card.key==="immunity"){state.players=state.players.map(p=>p.id===player.id?{...p,immunityActive:true}:p);return {ok:true,note:"Immunitet aktywny: najbliższy lincz zostanie anulowany."};}if(card.key==="doubleVote"){state.players=state.players.map(p=>p.id===player.id?{...p,doubleVoteArmed:true}:p);return {ok:true,note:"Podwójny głos aktywny na to głosowanie."};}if(card.key==="vest"){state.players=state.players.map(p=>p.id===player.id?{...p,vestActive:true}:p);return {ok:true,note:"Kamizelka aktywna: pierwszy nocny atak nie zabije."};}return {ok:false,note:"Ta karta jeszcze nie ma efektu."};}
function randomAliveTarget(excludeId){const candidates=state.players.filter(p=>p.alive&&p.id!==excludeId);if(!candidates.length)return null;return candidates[Math.floor(Math.random()*candidates.length)]||null;}
function skipCurrentPhase(){if(state.transitionData){handleTransitionConfirm();return;}if(state.phase==="lobby"){state.players=state.players.map(p=>({...p,ready:true}));checkLobbyCountdown();return;}if(state.phase==="roleReveal"){state.players=state.players.map(p=>({...p,roleAcknowledged:true}));beginStartCardInfoFlow();return;}if(state.phase==="startCardInfo"){state.startCardQueue=(state.startCardQueue||[]).map(item=>({...item,seen:true}));beginDeathGiftFlow();return;}if(state.phase==="deathGiftChoose"){if(state.awaitingDeathGiftFor){const receiver=randomAliveTarget(state.awaitingDeathGiftFor)||randomAliveTarget(null);if(receiver){giveDeathGift(state.awaitingDeathGiftFor,receiver.id);}else{beginGrantInfoFlow();}return;}beginGrantInfoFlow();return;}if(state.phase==="grantInfo"){state.privateNotes={};state.grantInfoQueue=[];finishGrantInfoFlow();return;}if(state.phase==="day"){alivePlayers().forEach(p=>{state.dayReadyMap[p.id]=true});pulseFade(()=>startVoting());return;}if(state.phase==="night"){const living=alivePlayers();living.forEach(actor=>{if(actor.nightSubmitted)return;const fallback=randomAliveTarget(null);const target=randomAliveTarget(actor.role==="detective"?actor.id:null)||fallback;if(!target)return;const actionType=actor.role==="mafia"?"kill":actor.role==="doctor"?"heal":actor.role==="detective"?"inspect":"dummy";state.nightActions[actor.id]={actorId:actor.id,targetId:target.id,actionType,submitted:true};if(actor.role==="mafia"){state.submittedNightTargets[actor.id]=target.id;delete state.pendingNightTargets[actor.id];}});state.players=state.players.map(p=>p.alive?{...p,nightSubmitted:true}:p);pulseFade(()=>resolveNightWithActions({...state.nightActions},[...state.players]));return;}if(state.phase==="voting"){const living=alivePlayers();living.forEach(actor=>{if(actor.voteSubmitted)return;const target=randomAliveTarget(actor.id)||randomAliveTarget(null);if(!target)return;state.votes[actor.id]=target.id;state.submittedVoteTargets[actor.id]=target.id;});state.players=state.players.map(p=>p.alive?{...p,voteSubmitted:true}:p);pulseFade(()=>resolveVoting());return;}}
function renderCardsOverlay(screen, sp){const cards=sp.cards.filter(c=>!c.used); if(!cards.length) return; const selected=cards[Math.min(state.selectedCardIndex,cards.length-1)]||null; const canPlay=!!selected && canUseCard(selected) && selected.meta && selected.meta.implemented; const message=selected && !canUseCard(selected) ? 'Nie możesz teraz zagrać tej karty.' : selected && !selected.meta.implemented ? 'Efekt tej karty nie jest jeszcze wdrożony.' : '&nbsp;'; screen.insertAdjacentHTML('beforeend', `<div class="fullscreen-overlay" id="cardsOverlay"><div class="title-top">Schowek kart</div><div class="fullscreen-overlay-center"><div style="width:100%"><div class="card-slider" id="cardSlider">${cards.map((card,index)=>`<div class="card-slide" data-card-index="${index}">${cardFaceHTML(card)}</div>`).join('')}</div><div class="card-selected-indicator">${cards.length ? `${Math.min(state.selectedCardIndex+1,cards.length)}/${cards.length}` : ''}</div></div></div>${bottomHTML({metaLines:[message],secondaryLabel:"Wróć",secondaryDisabled:false,secondaryId:"backFromCardsBtn",primaryLabel:"Zagraj",primaryDisabled:!canPlay,primaryId:"playCardBtn"})}</div>`); const slides=document.querySelectorAll('#cardSlider .card-slide'); bindPressAll(slides,(e)=>{state.selectedCardIndex=Number(e.currentTarget.getAttribute('data-card-index')||0); render()}); bindPress(document.getElementById('backFromCardsBtn'),()=>{state.cardsOverlayOpen=false;render()}); bindPress(document.getElementById('playCardBtn'),()=>{ if(!canPlay) return; const result=applyCardEffect(sp,selected); if(result&&result.note){state.privateNotes[sp.id]=result.note;} selected.used=true; state.cardsOverlayOpen=false; render(); }); }
function renderTransition(screen){const data=state.transitionData;const ackKey=`transition-${data.title}-${data.nextPhase}`;ensureAckFlow(ackKey);const sp=selectedPlayer();const alreadyAcked=isAckedInFlow(ackKey,sp.id);const privateNote=state.privateNotes[sp.id];screen.innerHTML=`<div class="transition-box"><div class="title-top">${data.title}</div><div style="flex:1;display:flex;align-items:center;justify-content:center"><div><div class="transition-message">${data.message.replace(/\n/g,"<br>")}</div>${privateNote?`<div class="transition-note">${privateNote}</div>`:""}</div></div></div>${bottomHTML({metaLines:[ackCountTextByKey(ackKey)],secondaryVisible:false,primaryLabel:data.button,primaryDisabled:alreadyAcked})}`;bindPress(document.getElementById("mainBtn"),()=>{acknowledgeFlow(ackKey,()=>handleTransitionConfirm())})}
function renderEnd(screen){screen.innerHTML=`<div class="title-top">Koniec gry</div><div style="margin-top:16px;text-align:center;font-size:34px;font-weight:700">Wygrywa ${state.winner||"—"}</div><div id="endGrid" class="end-grid"></div>${bottomHTML({metaLines:["&nbsp;"],secondaryVisible:false,primaryLabel:"Nowa gra"})}`;const endGrid=document.getElementById("endGrid");endGrid.innerHTML=state.players.map((player)=>{const roleClass=player.role?ROLE_META[player.role].endColor:"white";return `<div class="end-tile ${roleClass}"><div class="tile-left"><span style="display:flex;align-items:center;justify-content:center">${userIconSVG(14)}</span><span class="tile-name">${player.name}</span></div></div>`}).join("");bindPress(document.getElementById("mainBtn"),()=>resetGame())}
function renderSettings(){const wrap=document.getElementById('settingsGrid'); wrap.innerHTML=`<label class="settings-row"><span>Liczba mafiozów</span><div class="settings-inline"><button id="mafMinus" class="small-btn">-</button><span class="settings-value">${state.settings.mafiaCount}</span><button id="mafPlus" class="small-btn">+</button></div></label><label class="settings-row"><span>Karty na start</span><div class="settings-inline"><button id="cardMinus" class="small-btn">-</button><span class="settings-value">${state.settings.startCardsCount}</span><button id="cardPlus" class="small-btn">+</button></div></label><label class="settings-row"><span>Czas dnia</span><div class="settings-inline"><button id="dayMinus" class="small-btn">-</button><span class="settings-value">${formatSeconds(state.settings.daySeconds)}</span><button id="dayPlus" class="small-btn">+</button></div></label><label class="settings-row"><span>Czas głosowania</span><div class="settings-inline"><button id="voteMinus" class="small-btn">-</button><span class="settings-value">${formatSeconds(state.settings.votingSeconds)}</span><button id="votePlus" class="small-btn">+</button></div></label><label class="settings-row"><span>Czas nocy</span><div class="settings-inline"><button id="nightMinus" class="small-btn">-</button><span class="settings-value">${formatSeconds(state.settings.nightSeconds)}</span><button id="nightPlus" class="small-btn">+</button></div></label><label class="settings-row"><span>Włącz karty</span><input id="cardsToggle" type="checkbox" ${state.settings.enableCards?'checked':''}></label><label class="settings-row"><span>Lekarz</span><input id="doctorToggle" type="checkbox" ${state.settings.enableDoctor?'checked':''}></label><label class="settings-row"><span>Detektyw</span><input id="detectiveToggle" type="checkbox" ${state.settings.enableDetective?'checked':''}></label><div class="helper-note">Aktywne karty</div>${SPECIAL_CARDS.map(card=>`<label class="settings-row"><span>${card.name}</span><input class="card-setting" data-key="${card.key}" type="checkbox" ${state.settings.enabledCards[card.key]?'checked':''}></label>`).join('')}<div class="modal-actions"><button id="settingsCloseBtn" class="primary">Zamknij</button></div>`;
 bindPress(document.getElementById('mafMinus'),()=>{state.settings.mafiaCount=Math.max(1,state.settings.mafiaCount-1);resetReady();render()}); bindPress(document.getElementById('mafPlus'),()=>{state.settings.mafiaCount=Math.min(5,state.settings.mafiaCount+1);resetReady();render()}); bindPress(document.getElementById('cardMinus'),()=>{state.settings.startCardsCount=Math.max(0,state.settings.startCardsCount-1);resetReady();render()}); bindPress(document.getElementById('cardPlus'),()=>{state.settings.startCardsCount=Math.min(12,state.settings.startCardsCount+1);resetReady();render()}); bindPress(document.getElementById('dayMinus'),()=>{state.settings.daySeconds=Math.max(30,state.settings.daySeconds-15);resetReady();render()}); bindPress(document.getElementById('dayPlus'),()=>{state.settings.daySeconds=Math.min(900,state.settings.daySeconds+15);resetReady();render()}); bindPress(document.getElementById('voteMinus'),()=>{state.settings.votingSeconds=Math.max(10,state.settings.votingSeconds-5);resetReady();render()}); bindPress(document.getElementById('votePlus'),()=>{state.settings.votingSeconds=Math.min(300,state.settings.votingSeconds+5);resetReady();render()}); bindPress(document.getElementById('nightMinus'),()=>{state.settings.nightSeconds=Math.max(15,state.settings.nightSeconds-5);resetReady();render()}); bindPress(document.getElementById('nightPlus'),()=>{state.settings.nightSeconds=Math.min(600,state.settings.nightSeconds+5);resetReady();render()}); document.getElementById('cardsToggle').onchange=(e)=>{state.settings.enableCards=e.target.checked;resetReady()}; document.getElementById('doctorToggle').onchange=(e)=>{state.settings.enableDoctor=e.target.checked;resetReady()}; document.getElementById('detectiveToggle').onchange=(e)=>{state.settings.enableDetective=e.target.checked;resetReady()}; wrap.querySelectorAll('.card-setting').forEach(el=>el.addEventListener('change',(e)=>{state.settings.enabledCards[e.target.getAttribute('data-key')]=e.target.checked;resetReady()})); bindPress(document.getElementById('settingsCloseBtn'),()=>closeSettingsModal()) }
function render(){if(!state.selectedPlayerId&&state.players[0])state.selectedPlayerId=state.players[0].id;const sp=selectedPlayer();document.getElementById("testInfo").textContent=sp?`${sp.name} • ${sp.alive?"żyje":"martwy"} • ${sp.role?ROLE_META[sp.role].name:"brak roli"}`:"Brak aktywnego gracza";renderSettings();const screen=document.getElementById("screen");if(!sp&&state.phase!=="lobby"){screen.innerHTML="";return} if(state.phase==="grantInfo" && sp && !sp.alive){ nextGrantInfo(); return; } if(state.transitionData) renderTransition(screen); else if(state.phase==="lobby") renderLobby(screen,sp); else if(state.phase==="roleReveal") renderRoleReveal(screen,sp); else if(state.phase==="startCardInfo") renderCardInfo(screen,sp); else if(state.phase==="deathGiftChoose") renderDeathGiftChoose(screen,sp); else if(state.phase==="grantInfo") renderGrantInfo(screen,sp); else if(state.phase==="night") renderNight(screen,sp); else if(state.phase==="day") renderDay(screen,sp); else if(state.phase==="voting") renderVoting(screen,sp); else if(state.phase==="ended") renderEnd(screen)}
function refreshVisibleTimers(){if(state.phase==="lobby"&&state.lobbyEndsAt){state.lobbyCountdown=secondsLeftFromEnd(state.lobbyEndsAt)}if(state.phase==="roleReveal"&&state.revealEndsAt){state.revealCountdown=secondsLeftFromEnd(state.revealEndsAt)}if(["night","day","voting"].includes(state.phase)&&state.phaseEndsAt){state.phaseSecondsLeft=secondsLeftFromEnd(state.phaseEndsAt)}render()}
function openJoinModal(){document.getElementById("joinModal").classList.add("show");document.getElementById("joinNameInput").focus()}function closeJoinModal(){document.getElementById("joinModal").classList.remove("show")}function openSettingsModal(){document.getElementById("settingsModal").classList.add("show")}function closeSettingsModal(){document.getElementById("settingsModal").classList.remove("show");render()}
bindPress(document.getElementById("nextPlayerBtn"),()=>selectNextPlayer());bindPress(document.getElementById("skipPhaseBtn"),()=>skipCurrentPhase());bindPress(document.getElementById("resetBtn"),()=>resetGame());bindPress(document.getElementById("settingsBtn"),()=>openSettingsModal());bindPress(document.getElementById("joinAddBtn"),()=>addPlayer());
document.getElementById("joinModal").addEventListener("click",(e)=>{if(e.target.id==="joinModal")closeJoinModal()});document.getElementById("settingsModal").addEventListener("click",(e)=>{if(e.target.id==="settingsModal")closeSettingsModal()});document.getElementById("joinNameInput").addEventListener("keydown",(e)=>{if(e.key==="Enter")addPlayer()});document.addEventListener("visibilitychange",()=>{if(!document.hidden){refreshVisibleTimers()}});
render();checkLobbyCountdown();
